### ISSUE TITLE
How to use, how to import

### ISSUE THREAD

**Issue by frederikhors** [porsager/rollup-plugin-svgo#1]
Can I ask you how to import an svg in my html?

**Comment by porsager** [comment]
Could you describe in a bit more detail what you're trying to achieve? This is a plugin that imports svg's as strings in `.js`

**Comment by porsager** [comment]
Feel free to reopen if you still need help ;)

**Comment by meh** [comment]
I'm gonna jump in here because it's kind of related.

I'm trying to [svg-icons](https://github.com/AlexxNB/rollup-plugin-svg-icons) + [inline-svg](https://github.com/sionzeecz/rollup-plugin-inline-svg) + this plugin.

I can't seem to figure out how to make everyone work together, any hints?

Thanks!
